Repository YCP-Swarm-Robotics-Capstone-2020-2021/swarm-website-visualization, pull requests merged in 2020-10, with the labels that each got.

#36 feature/pointerLock
  Cargo.toml
  src/lib.rs
Labels: Enhancement

#39 feature/pointerLock
  Cargo.toml
  src/lib.rs
Labels: Enhancement

#44 Feature/mesh loader
  .gitattributes
  Cargo.toml
  Cube.obj
  shaders/texture_vert.glsl
  src/gfx/mesh.rs
  src/gfx/mod.rs
  src/gfx/renderer/mod.rs
  src/gfx/renderer/vertex.rs
  src/lib.rs
Labels: task

#45 Feature/wasm tests
  src/gfx/gl_object/buffer.rs
  src/gfx/gl_object/shader_program.rs
  src/lib.rs
  src/test_util.rs
  wasmtest.py
Labels: task

#48 Feature/resource loader
  Cargo.toml
  src/gfx/gl_object/shader_program.rs
  src/gfx/renderer/renderer.rs
  src/lib.rs
  src/resource/loader.rs
  src/resource/manager.rs
  src/resource/mod.rs
  testsite.html
Labels: task

#52 Fix RefMut compiler related bug
  src/gfx/render_loop.rs
Labels: bug

#53 Hotfix/binary git atrrib
  .gitattributes
  Cube.obj
  resources/images/tex_atlas.pbm
Labels: bug

#54 Update files that were in git lfs
  resources/models/robot.obj
  resources/models/room.obj
Labels: bug
